### ISSUE TITLE
Why is this api better than next-connect?

### ISSUE THREAD

**Issue by bmstefanski** [neg4n/next-api-compose#4]
As in the title, why should I use this and not https://github.com/hoangvvo/next-connect#readme ?

**Comment by neg4n** [comment]
Hey. I wouldn't say its better - I'd rather say it is different.

I've been using `next-connect` for a while but I found its API a bit unintuitive. Probably because of combining routing functionality (which i believe Next.js handles very well on its own) with middleware layer. I also had some issue most likely related to [route pattern matching][next-connect-pattern-issue] although I did not take advantage of that functionality in my code at all. I neither found fix nor workaround.

I took an opportunity and I've created `next-api-compose`  which completly fit my needs.

Some `next-api-compose` features that I haven't seen in `next-connect`:
- its designed with higher order function middleware approach (as recommended in [Next.js docs section about writing middleware.][next-docs-middleware]) that relies on intercepting `req`and `res` objects.
- it has utility that helps with compatibility and also significantly reduces boilerplate code when it comes to using multiple [Connect][connect]/[Express][express] middleware, by converting them to higher order functions and leveraging the original middleware.
- it has **no dependencies at all** - the area of occurring for errors is small.
- it is designed specially for [Next.js][next-homepage] - mentioned earlier area is even smaller.

... and generally I thought sharing `next-api-compose` with the world would be super cool :sunglasses:

[connect]: https://github.com/senchalabs/connect
[express]: https://expressjs.com
[next-homepage]: https://nextjs.org/ 
[next-connect-pattern-issue]: https://github.com/hoangvvo/next-connect/issues/131
[next-docs-middleware]: https://nextjs.org/docs/api-routes/api-middlewares

**Comment by bmstefanski** [comment]
Yeah, that makes perfect sense. Thanks and stay sigma :)!
